### ISSUE TITLE
De Boterhamshow crashes my Kodi

### ISSUE THREAD

**Issue by batje** [Opvolger/plugin.video.uzg#10]
I added a De Boterhamshow to my favorites and Kodi chocked on this image:

http://mediadb.omroep.nl/assets/003/639/898.jpg

This was in the logs:

> 11:38:30.660 T:1732936608  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.6), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
> 11:38:31.273 T:1759507360 WARNING: CreateLoader - unsupported protocol(activatewindow(10025,"plugin) in activatewindow(10025,"plugin://plugin.video.uzg/afleveringen/KN_1680571/",return).tbn
> 11:38:31.274 T:1759507360 WARNING: CreateLoader - unsupported protocol(activatewindow(10025,"plugin) in activatewindow(10025,"plugin://plugin.video.uzg/afleveringen/POW_03709516/",return).tbn
> 11:38:31.277 T:1759507360 WARNING: CreateLoader - unsupported protocol(activatewindow(10025,"plugin) in activatewindow(10025,"plugin://plugin.video.uzg/afleveringen/2566/",return).tbn
> 11:38:31.295 T:1759507360 WARNING: CreateLoader - unsupported protocol(activatewindow(10025,"plugin) in activatewindow(10025,"plugin://plugin.video.uzg/afleveringen/POW_00887141/",return).tbn
> 11:38:31.303 T:1759507360 WARNING: CreateLoader - unsupported protocol(activatewindow(10025,"plugin) in activatewindow(10025,"plugin://plugin.video.uzg/afleveringen/POMS_S_EO_2708703/",return).tbn
> 11:38:31.684 T:1716159392 WARNING: CSkinInfo: failed to load skin settings
> 11:38:52.585 T:1759507360   ERROR: COMXCoreComponent::WaitForOutputDone OMX.broadcom.image_encode wait event timeout
> 11:38:52.586 T:1759507360   ERROR: COMXReEnc::ReEncode http://mediadb.omroep.nl/assets/003/639/898.jpg m_omx_encoder.WaitForOutputDone result(0x80001011)
> 11:38:52.590 T:1848636320   ERROR: COMXCoreComponent::DecoderEventHandler OMX.broadcom.image_decode - OMX_ErrorStreamCorrupt, Bitstream corrupt
> 11:38:52.590 T:1759507360   ERROR: COMXCoreComponent::WaitForCommand - OMX.broadcom.image_decode failed with omx_err(0x8000100b)
> 11:39:03.124 T:1759507360   ERROR: COMXCoreComponent::WaitForOutputDone OMX.broadcom.resize wait event timeout
> 11:39:03.124 T:1759507360   ERROR: COMXImageDec::Decode m_omx_resize.WaitForOutputDone result(0x80001011)
> 11:39:03.124 T:1759507360  NOTICE: DecodeJpeg: unable to decode http://mediadb.omroep.nl/assets/003/639/898.jpg 811x540
 

Kodi died with an out of memory:

> [  380.372249] Out of memory: Kill process 1067 (kodi.bin) score 894 or sacrifice child
> [  380.372354] Killed process 1067 (kodi.bin) total-vm:1398376kB, anon-rss:693112kB, file-rss:0kB, shmem-rss:0kB
> [  380.499513] oom_reaper: reaped process 1067 (kodi.bin), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
> [  432.024008] kodi.bin invoked oom-killer: gfp_mask=0x26080c0(GFP_KERNEL|__GFP_ZERO|__GFP_NOTRACK), nodemask=0, order=0, oom_score_adj=0
> 

Running on a Raspberry Pi3 with LibreElec, all latest versions. Kodi 17.6 and LibreElec 8.1.2

**Comment by Opvolger** [comment]
Onjuist plaatje kan kodi niet aan blijkbaar
