### ISSUE TITLE
Opening the plugin crashes Kodi

### ISSUE THREAD

**Issue by bringabong** [Opvolger/plugin.video.uzg#11]
When opening the UZG plugin, while loading the index, Kodi crashes:

23:52:54.224 T:1686242208   DEBUG: CWebServer[80]: request received for /image/image%3A%2F%2Fhttp%253a%252f%252fmediadb.omroep.nl%252fassets%252f003%252f458%25
2f093.jpg%2F
23:52:54.226 T:1686242208    INFO: easy_aquire - Created session to http://mediadb.omroep.nl
23:52:54.333 T:1686242208   DEBUG: CurlFile::Open(0x5f292918) http://mediadb.omroep.nl/assets/003/458/093.jpg
23:52:55.186 T:1859122080   DEBUG: CWebServer[80]: request received for /jsonrpc
23:52:59.828 T:1686242208   DEBUG: Previous line repeats 7 times.
23:52:59.828 T:1686242208 WARNING: COMXImageFile::GetCodingType Only YUV images are supported by decoder
23:52:59.828 T:1686242208   DEBUG: COMXImageFile::ReadFile http://mediadb.omroep.nl/assets/003/458/093.jpg GetCodingType=0x7fffffff (11369x8126)
23:52:59.892 T:1686242208   DEBUG: CCurlFile::GetMimeType - http://mediadb.omroep.nl/assets/003/458/093.jpg -> image/jpeg
23:52:59.893 T:1686242208   DEBUG: CurlFile::Open(0x5040e008) http://mediadb.omroep.nl/assets/003/458/093.jpg
23:53:01.275 T:1859122080   DEBUG: CWebServer[80]: request received for /jsonrpc
23:53:02.293 T:1686242208   DEBUG: Previous line repeats 1 times.
23:53:02.293 T:1686242208 WARNING: COMXImageFile::GetCodingType Only YUV images are supported by decoder
23:53:02.293 T:1686242208   DEBUG: COMXImageFile::ReadFile http://mediadb.omroep.nl/assets/003/458/093.jpg GetCodingType=0x7fffffff (11369x8126)
23:53:02.293 T:1686242208  NOTICE: LoadJpeg: unable to load http://mediadb.omroep.nl/assets/003/458/093.jpg
23:53:02.296 T:1686242208   DEBUG: CurlFile::Open(0x5f292918) http://mediadb.omroep.nl/assets/003/458/093.jpg

Kodi crashes on 'Out of memory':

[2170502.948126] Out of memory: Kill process 12530 (kodi.bin) score 888 or sacrifice child
[2170502.948283] Killed process 12530 (kodi.bin) total-vm:1470416kB, anon-rss:688148kB, file-rss:0kB, shmem-rss:64kB
[2170503.076762] oom_reaper: reaped process 12546 (kodi.bin), now anon-rss:4kB, file-rss:8kB, shmem-rss:64kB

This is while running Kodi 17.3 on Openelec 8.0.4, UZG plugin version 1.3.1

**Comment by Opvolger** [comment]
Plaatje was geen juist plaatje. volgens mij is hij nu weer oke.
Als NPO dus een niet compleet of beschadigd plaatje doorgeeft, zal hij crashen.
