### ISSUE TITLE
No recent 'NOS Journaal' episodes

### ISSUE THREAD

**Issue by huiser** [Opvolger/plugin.video.uzg#12]
Hi,

since a few days I noticed something strange. Recent episodes of NOS Journaal are not visible in Uitzending Gemist addon.

**Comment by eflukx** [comment]
On my Kodi only "Recent programs" shows anything, most of the other programs show no episodes. My guess is this has something to do with the move to "NPO Start".

**Comment by Opvolger** [comment]
Ik heb niks veranderd aan de uitvraag. NPO zal wel wat veranderd hebben.

**Comment by pooh22** [comment]
Ik zie ook een probleem, bijvoorbeeld met NOS Olympische spelen. Sinds 16-02-2018 geen nieuwe episodes meer vanaf 06:00. Op de website van uitzendinggemist is wel alles bijgewerkt...

**Comment by Opvolger** [comment]
Helaas is in de zomer van 2017 een nieuwe api online gekomen, deze ondersteun ik niet en kan ik ook niet gaan ondersteunen. (api key nodig, welke ik nu niet heb en geblokkkeerd zal gaan worden als ik deze opensource vrij geef.).

**Comment by pooh22** [comment]
En de oude api werkte nog tot net midden in de olympische spelen :-(???
Anyway, zie je een mogelijkheid om uitzending gemist te laten werken op kodi?

**Comment by Opvolger** [comment]
Hij werkt nog, maar ontvangt geen nieuwe afleveringen meer. Ik zie wel mogelijkheden. Maar zit midden in een verhuizing en veel deadlines (overwerken). Dus heb er helaas even geen tijd voor.

**Comment by pooh22** [comment]
ok, alle begrip voor je situatie, blij dat je wel mogelijkheden ziet :-)

**Comment by pooh22** [comment]
Ter info, het lijkt erop dat het een tijdelijk probleem was, afgelopen week waren de uitzendingen van de olympische spelen weer te vinden in uitzending gemist. Ik durf iig niet te stellen dat er een bug of een api change de oorzaak was.
