### ISSUE TITLE
Lijst met afleveringen toont tijden, geen datums

### ISSUE THREAD

**Issue by Roelofpieter** [Opvolger/plugin.video.uzg#13]
Ik draai kodi via OSMC op een Raspberry Pi. Na het selecteren van een programma in de uitzendinggemist addon zie je een lijst met episodes. Je ziet de starttijd en de titel van de episode. Deze lijst ziet er zo uit:

- (20:30:00) - Wie is de Mol?
- (20:30:00) - Wie is de Mol?
- ...

Niet handig. Ik zie liever de datum waarop een episode uitgezonden werd. Ik heb dit bij mezelf aangepast (Hax0r l33t! :-) ) in regel 106 van plugin.video.uzg/resources/lib/uzg.py :

Van:
`'label': '(' + post['TimeStamp'].split('T')[1] + ') - ' + titelnaam,`

Naar:
`'label': '(' + post['date'] + ') - ' + titelnaam,`

Nu zie ik:
- (13-01-2018) - Wie is de Mol?
- (20-01-2018) - Wie is de Mol?
- ...

Beter. Is het een idee dit in de code hier over te nemen?

**Comment by Opvolger** [comment]
Dit kan, ik had het gedaan omdat destijds het journaal in de titel alleen de  datum bevatte en geen tijd.
Ik zal er binnenkort naar kijken of ik dit op kan nemen.

**Comment by jorissteyn** [comment]
De standaard skin in Kodi toont de datums rechts uitgelijnd in de lijstweergave. Dat de datum niet zichtbaar is in de standaard OSMC skin is een beperking van OSMC. De datum opnemen in het label zorgt ervoor dat niet-OSMC gebruikers de datum dubbel zien. Het lijkt me het beste om gewoon de Kodi skin te gebruiken in OSMC als je de datum van uitzending graag wil zien.

Ik begrijp nu waarom de tijd in het label is opgenomen. Dat is vanuit UX oogpunt dus heel wenselijk in sommige gevallen, maar meestal neemt het de schaarse ruimte op mijn telefoon in beslag waardoor de titel van de aflevering niet volledig zichtbaar is.

Ik heb een voorstel uitgewerkt in PR #14, kort samen gevat:

 * toon de tijd alleen wanneer er meerdere afleveringen op dezelfde dag zijn uitgezonden
 * tijd tussen haakjes *achter* de naam van de aflevering, niet ervoor
 * geen seconden weergeven: HH:MM

**Comment by Opvolger** [comment]
Volgens mij al opgelost in 1.3.2 en in 2.0.0 (KODI 18)
