### ISSUE TITLE
NPO API changed

### ISSUE THREAD

**Issue by ApexAlpha** [Opvolger/plugin.video.uzg#2]
The NPO has changed its API again it seems. None of the streams work now, they all return the same error message.

Seems related to: https://github.com/bosel/plugin.video.nederland24/issues/14

If you need logs or anything else please ask.

**Comment by Forage** [comment]
I pussose this one can be closed now?

**Comment by ApexAlpha** [comment]
Yes, must've forgot about it. Thanks for reminding.
