### ISSUE TITLE
no picture

### ISSUE THREAD

**Issue by Hochiss** [Opvolger/plugin.video.uzg#23]
Dears..
thanks for this great plugin, heard a lot from forums.
I tried but no picture or sound, only the subtitle can be seen. It looks as if it covered with "white blanket"? please check and help?

Here my settings:
------
OS: Android 5.1.0 API Level 22 (Kernel: Linux 3.10 61+)
HW: AArch 64 Processor rev 2(MT8693 + Power VR GX6250) | RAM:2G | MEM: 8G
SW: KODI 17.6
Installation: zip or github browser
Location: NL

please let me know if you need any further diagnosis info. 
Thanks!

**Comment by bartmans** [comment]
Most recent versions only work in Kodi 18 / 18.1.

**Comment by Opvolger** [comment]
Yep. Only 18.x or later
