### ISSUE TITLE
Addon Uitzending gemist werkt niet meer

### ISSUE THREAD

**Issue by saba1970** [Opvolger/plugin.video.uzg#33]
Hallo Bas,

vanmorgen probeerde ik de addon Uitzending gemist te starten. Starten ging goed, maar als ik daarna op een letter klikte kwam er een error.
Ik heb dit probleem op 2 raspberry pi's 3B.

Weet jij hoe dit kan?

Alvast bedankt.

**Comment by saba1970** [comment]
Hier de logging:
https://paste.kodi.tv/qipagusebu

**Comment by gvlierop** [comment]
Hallo Saba, Zojuist even bij mij getest maar alles werkt zoals het hoort. Ik gebruik de laatste versie 3.4.2. https://github.com/Opvolger/plugin.video.uzg/releases/download/3.4.2/plugin.video.uzg-3.4.2.zip

**Comment by saba1970** [comment]
Hallo gvlierop,

Bedankt.
je hebt gelijk. Ik had versie 3.4.1. Ik heb nu 3.4.2 geïnstalleerd en alles werkt weer.
