### ISSUE TITLE
Zoeken geeft 2324 resultaten

### ISSUE THREAD

**Issue by oegstgeest** [Opvolger/plugin.video.uzg#38]
Wanneer ik op de '?' klik en een zoekopdracht geef ('flikken' in mijn geval) krijg ik een lijst met 2324 resultaten terug, dat zou een veel kortere lijst moeten zijn. Ik heb versie 3.5.0 geïnstalleerd.

**Comment by oegstgeest** [comment]
... en ik had er natuurlijk gelijk bij moeten zeggen dat dit versie 3.5.0 betreft, die net twee weken uit is.

**Comment by gvlierop** [comment]
De parameter query='+tekst), gebruikt in uzg.py  is schijnbaar obsolete geworden. 
Er is door mij geen beschrijving of instructie gevonden voor aansturing van de API.
Het wachten is op BAS ;) 

(def getQueryPage(self, tekst):
        # default is page 1
        return SerieItems('https://start-api.npo.nl/media/series?query=' + tekst).uzgitemlist

**Comment by Opvolger** [comment]
Api is gewijzigd en ik kan niet snel vinden naar wat.
functie werkt nu dus niet, ik zie nu ook dat hij gewoon alles ophaalt helaas.

**Comment by Opvolger** [comment]
Opgelost in 3.6.1

**Comment by oegstgeest** [comment]
Yes, perfect! 
Ook leuk dat de live-streams er nu in zitten.
