### ISSUE TITLE
Kijken van live-uitzendingen

### ISSUE THREAD

**Issue by marcelkorpel** [Opvolger/plugin.video.uzg#39]
Hoewel het misschien buiten de scope valt van deze plugin, vraag ik me af of het met een kleine aanpassing niet ook mogelijk is de live-uitzending van NPO 1, 2, en 3 en de themakanalen te bekijken. Deze zijn tegenwoordig eveneens met DRM versleuteld en ik kan wel achter de video-url's komen, maar deze niet zonder meer starten met Kodi.

De op Kodi.wiki genoemde plugin Nederland24 is [al drie jaar](https://github.com/bosel/plugin.video.nederland24) niet meer bijgewerkt en biedt dus uiteraard geen ondersteuning voor DRM.

**Comment by bartmans** [comment]
Kijk eens naar de plugin Retrospect: https://www.rieter.net/content/

Ik gebruik zowel UZG als Retrospect en vind beide mooie plugins om legaal (ik woon in NL) alles online te kunnen kijken.

**Comment by bartmans** [comment]
En ben dus beide makers dankbaar (vooral nu in Coronadays).

**Comment by Opvolger** [comment]
https://github.com/Opvolger/plugin.video.hanssettings <- allemaal streams ook voor NPO

**Comment by marcelkorpel** [comment]
Dank beide, dit biedt inderdaad wat ik zocht.
