### ISSUE TITLE
Unusable label

### ISSUE THREAD

**Issue by Forage** [Opvolger/plugin.video.uzg#4]
Each episode have a "(xx:xx:xx)" label in front of it's title. In it's current form they don't provide much value. If you go e.g. to the episodes of "De Wereld Draait Door" you will see that they all have the name "(19:00:00) - De Wereld Draait Door". I don't know what this "(19:00:00)" part means, but I assume it would have been a date in the past and now it's being parsed incorrectly because it's format has changed or something.

It would be good to get this fixed.

**Comment by ApexAlpha** [comment]
19:00 is the time the broadcast on TV starts. This is usefull for shows that have multiple broadcast in one day. Like the News.

**Comment by Forage** [comment]
Aha.
Could the time at least be reduced to just hour and minutes than? And what about dropping the program title, unless the title can change, and sticking in a date instead?

**Comment by ApexAlpha** [comment]
I'm not a developer but that sounds doable. The second idea is a good one too.

**Comment by Opvolger** [comment]
I don't see the problem. De time is for the ordering. I can only order on date, not date/time.
When there is a time-prefix then show with are more then on a day it is ordered the right way.

**Comment by Forage** [comment]
I believe that we are misunderstanding each other. Let's start over.

At first I though the "(19:00:00)" part in "(19:00:00) - De Wereld Draait Door" was a bug. It was the last ":00" part that caused this. Because of @ApexAlpha I learned it was (obviously) meant to be the time. I would have known if I would have looked at more shows, but still.

I assume the last ":00" part is for the seconds. Which seems to me like being redundant information. If there is even a second show starting just a few seconds later, than it's likely to be a different show, in which case the sorting order doesn't matter that much.
A distinction should be made between what is valuable for the user and what in only needed in the background for functioning properly. So I suggest removing the seconds to make thing a bit cleaner.
You would get "(19:00) - De Wereld Draait Door"

A show like DWDD has one each day at the same time. But there's only a time in the name, no date. This prevents me from quickly finding a show of a specific day.
I suggest adding a date, in addition to the time. Sticking to the date format one set in the general Kodi preference.
You would get similar to "(2015-03-31 19:00) - De Wereld Draait Door"

A third part of my suggestion is to remove the show name from the items, if possible. All the names are the same in a specific folder. You should know which show you selected, and if not, it should be made more clear. This would allow you to remove the name from each item. This, unless a show in a specific folder can have different names.
If it's possible to remove the names, you would just get "2015-03-31 19:00" items.
