### ISSUE TITLE
Geen nieuwe afleveringen 

### ISSUE THREAD

**Issue by pjvanswaaij** [Opvolger/plugin.video.uzg#40]
Voor sommige uitzendingen verschijnen geen nieuwe afleveringen...helaas is dit ook voor het allerbeste tv programma Bed en Breakfast van omroep max......snik 😢

**Comment by lymon66** [comment]
Heb zelfde probleem, maar het lijkt alleen op te treden bij series met "seizoen" subfolders.

**Comment by Opvolger** [comment]
Ik zie het probleem, ze plaatsten de nieuwe aflevering niet meer in de Seizoen 2020 map, maar direct onder "Bed en Breakfast". Erg vreemd. 
Vroeger waren het of Seizoen of afleveringen. nu doen ze beide.
Zal het proberen te fixxen, dat ik deze ook meeneem.

**Comment by Opvolger** [comment]
Nee, dat was het niet. ik zie het al... nieuwe afleveringen zitten achter de betaal-muur :(
https://www.npostart.nl/bed-breakfast/POW_03094259
Hier zie je dat ik alleen de 2 afleveringen weer geef van 2020 welke niet achter de betaal-muur zitten. Hier kan/mag ik helaas niks aan doen.

**Comment by gvlierop** [comment]
De parameter query='+tekst), gebruikt in uzg.py is schijnbaar obsolete geworden.
Er is door mij geen beschrijving of instructie gevonden voor aansturing van de API.
Het wachten is op BAS ;)

(def getQueryPage(self, tekst):
# default is page 1
return SerieItems('https://start-api.npo.nl/media/series?query=' + tekst).uzgitemlist
