### ISSUE TITLE
Video's laden niet

### ISSUE THREAD

**Issue by yannickdoteu** [Opvolger/plugin.video.uzg#47]
Hey Bas / opvolger!

Met veel plezier heb ik je plugin gebruikt, want hierdoor heb ik van kwaliteit NPO programma's kunnen genieten zonder de onzin van een smart-tv of tv-abonnement. Gewoon met mijn raspberry pi en jouw plugin.

Sinds een week ongeveer laden video's niet meer. Ik heb de plugin opnieuw geprobeerd te installeren maar ook dat haalt niks uit. Verder werkt alles gewoon. Ik dingen opzoeken etc. Live tv doet het ook niet meer.

Als ik een beetje handig was geweest had ik er misschien zelf nog wat van kunnen proberen te maken en een pull request te sturen maar zo handig ben ik lang nog niet.

Kortom, ik zou het heel erg gaaf vinden als je misschien de tijd vindt om ernaar te kijken. Als er iets is wat ik voor je kan doen om je te helpen hoor ik het graag.

Heel erg bedankt voor de plugin die je hebt gemaakt en die mijn leven wat beter heeft gemaakt.

Yannick

**Comment by basrieter** [comment]
WideVine is het probleem: https://www.matthuisman.nz/2021/05/widevine-arm-broken.html. Zie ook hier: https://github.com/retrospect-addon/plugin.video.retrospect/issues/1547

**Comment by yannickdoteu** [comment]
Dankjewel!

**Comment by yannickdoteu** [comment]
> WideVine is het probleem: https://www.matthuisman.nz/2021/05/widevine-arm-broken.html. Zie ook hier: [retrospect-addon/plugin.video.retrospect#1547](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1547)

Dankjewel!
