### ISSUE TITLE
Haperend afspelen met widevine 14268.67.0

### ISSUE THREAD

**Issue by lymon66** [Opvolger/plugin.video.uzg#49]
Er lijken problemen met UZG icm. Widevine 14268.67.0 (de nieuwste versie op dit moment) op arm devices
Het lijkt nog het meest op een buffering probleem (haperend afspelen)
Netflix en andere addons die ook widevine gebruiken lijken deze problemen niet te hebben met deze versie van widevine.

Heb als workaround een oudere versie van Widevine teruggezet (v14150.64.0) en hier zijn geen problemen meer.

**Comment by averaart** [comment]
Beste @lymon66,

Kun je misschien omschrijven hoe je de vorige versie van widevine terugzet? Ik kamp met hetzelfde probleem.

**Comment by lymon66** [comment]
> Beste @lymon66,
> 
> Kun je misschien omschrijven hoe je de vorige versie van widevine terugzet? Ik kamp met hetzelfde probleem.

Dit kun je regelen binnen de Inputstream Helper addon --> Restore Widevine CDM Library.
Je krijgt dan een keuzemenu met oude(re) versies van widevine die je kunt terugzetten. Meestal moet je wel even herstarten na de restore voordat het werkt.

**Comment by lymon66** [comment]
Heb zojuist de meest recente Widevine (v 14324.62.0) geinstalleerd en hiermee lijkt uzg ook weer normaal af te spelen.

**Comment by lymon66** [comment]
Probleem is nog steeds aanwezig ?
Heb het zojuist even getest met de huidige/nieuwste versie van Widevine (v14388.62.0).
Ook installatie van de nieuwste versie van de Inputstream helper (0.59) helpt niet
Probleem van het haperen is aanwezig bij zowel bij Kodi 18 als 19
Widevine 14150.87.0 lijkt de laatste versie te zijn waarbij UZG nog wel normaal werkt, maar deze zal op termijn gaan "verlopen" en daarna wordt je gedwongen een nieuwe(re) versie te installeren.

**Comment by orthello** [comment]
> Probleem is nog steeds aanwezig ? Heb het zojuist even getest met de huidige/nieuwste versie van Widevine (v14388.62.0). Ook installatie van de nieuwste versie van de Inputstream helper (0.59) helpt niet Probleem van het haperen is aanwezig bij zowel bij Kodi 18 als 19 Widevine 14150.87.0 lijkt de laatste versie te zijn waarbij UZG nog wel normaal werkt, maar deze zal op termijn gaan "verlopen" en daarna wordt je gedwongen een nieuwe(re) versie te installeren.

Dit heeft niet met UZG zelf te maken maar met WideVine. Of Inputstream Helper/Adaptive.
Ook andere (niet UZG) gebruikers ervaren dit probleem met plugins die afhankelijk zijn van WideVine/Inputstream Helper/Adaptive. Welke uit het rijtje de echte boosdoener is (mij nog) niet helemaal duidelijk. Het probleem ontstond in elk geval na een update van WideVine. 

Voor een ieders administratie en voor hen die zoeken naar een werkende combinatie van versies:
De laatst bekende werkende **WideVine** versie betreft **4.10.2252.0** (Uit **Chrome OS image 13505.111.0**)
Ikzelf draai **Kodi 19.4** met **InputStream Helper 0.5.8+matrix.1** en **InputStream Adaptive 19.0.3**
Ik heb het aantal te bewaren updates/backups van WideVine zo hoog mogelijk gezet en de auto update van WideVine voorlopig uitgeschakeld.

**Comment by Opvolger** [comment]
Dan ligt het probleem niet bui UZG maar bij WideVine/InputstreamAdaptive. Ik lever alleen maar de links van de video in mijn plugin.
