### ISSUE TITLE
NPO Plus ondersteuning

### ISSUE THREAD

**Issue by batje** [Opvolger/plugin.video.uzg#51]
Met NPO Plus ondersteuning zou deze plugin n*o*g fijner zijn.  Dat gaan mijn kunnen helaas te boven.

**Comment by basrieter** [comment]
Retrospect heeft onderstuning voor NPO Plus.

**Comment by Opvolger** [comment]
Helaas heb ik geen plus abbonement, dus kan ik niet achterhalen hoe dit werkt. De plugin welke nu is gemaakt is ook met try and error gemaakt met de website en het verkeer van de app achterhalen.
