### ISSUE TITLE
Nieuwe API zonder terug in de tijd

### ISSUE THREAD

**Issue by Forage** [Opvolger/plugin.video.uzg#58]
De nieuwe versie werkt netjes met de nieuwe API, dank voor de moeite.

Met 4.0.3 kan ik echter niet terug in de tijd. Neem bijvoorbeeld het NOS Journal. Ik krijg een complete pagina met de laatste uitzendingen, maar ik kan niet verder terug in de tijd om nu om 18:00 bijvoorbeeld het journaal van gisteren om 18:00 te kunnen kijken.

Is dit een API beperking, iets op jouw todo lijst, of over het hoofd gezien?

**Comment by Opvolger** [comment]
ik zie geen paging techniek, op de website kan je nu ook niet oudere afleveringen aanklikken.
je kan ze wel opzoeken, dus ze staan wel in de database ergens. Als ik de formatering omdraai zie ik ook hele oude journaals : https://npo.nl/start/api/domain/programs-by-series?seriesGuid=5328ea0b-beff-4c14-959e-675cc6eb8261&sort=firstBroadcastDate maar nog geen idee hoe ik "naar een volgende pagina" kan gaan met meer (oudere) afleveringen

**Comment by Forage** [comment]
Ik zie het ja. Zo ook in de app is het niet mogelijk.
Verschillende shows met vele afleveringen zijn op deze manier niet meer volledig te zien. Dit lijkt mij niet de bedoeling en ik vermoed dan ook dat het een tijdelijke tekortkoming zal zijn.
Ik kan ze voor de lol eens een email sturen en ze de situatie voorleggen.

**Comment by bartmans** [comment]
Vast n scrumteam dat onder druk van de stakeholders de mvp net zo lang gedownsized heeft tot hun sprintdoel gehaald werd. De rest van de stories op de backlog geschoven. Maw recht geluld wat n bijzondere kromme app is tot nu toe.

**Comment by YeRonim** [comment]
Ik heb zojuist kodi geinstalleer op ubuntu. Ik kwam deze app tegen en heb de zip geinstalleerd. Echter krijg ik een foutmelding als ik een programma wil afspelen. Volgens mij is de laatste update in oktober gedaan toch? 
Doe ik iets verkeerd?

**Comment by Forage** [comment]
@YeRonim dat is een ander probleem, een ander onderwerp dan hier besproken. Dus een nieuwe issue voor aanmaken.

Tegelijkertijd, terug in de tijd gaan gaat er blijkbaar niet meer van komen met de nieuwe API. Ik had eerder al met support contact opgenomen, maar ze doen heel erg hun best het niet te begrijpen. Ik sluit deze issue dan ook maar gelijk.

**Comment by YeRonim** [comment]
Ooh ik zie h

> @YeRonim dat is een ander probleem, een ander onderwerp dan hier besproken. Dus een nieuwe issue voor aanmaken.
> 
> Tegelijkertijd, terug in de tijd gaan gaat er blijkbaar niet meer van komen met de nieuwe API. Ik had eerder al met support contact opgenomen, maar ze doen heel erg hun best het niet te begrijpen. Ik sluit deze issue dan ook maar gelijk.

Oh sorry ik zie het.. geen idee waardoor ik deze post op de verkeerde plek heb geplaatst..
