### ISSUE TITLE
NPO start werkt niet meer

### ISSUE THREAD

**Issue by ErikBrown2** [Opvolger/plugin.video.uzg#59]
NPO start werkt niet meer. De opties Live kanalen en Alle programma's geven de foutmelding "NPO Start error, check the log for more information". De optie Zoeken geeft wel de lijst met programma's weer maar als je er één van kiest dan krijg je dezelfde fout melding".

**Comment by Opvolger** [comment]
Ik zie het, geen journaal vanavond :(

Zal er zo even naar kijken.

**Comment by Opvolger** [comment]
Opgelost in 4.0.4

**Comment by ErikBrown2** [comment]
Dank je wel voor de snelle fix.
