### ISSUE TITLE
HTTP Error 410: Gone  

### ISSUE THREAD

**Issue by OnePlus3T** [Opvolger/plugin.video.uzg#6]
Let me start by thanking you on behalf of my kids for this great plugin.
Unfortunately it broke (because of changes by npo ?) 
Excerpt form temp/kodi.log:
File "/home/kodi/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 73, in get_play_url
  data = self.__get_data_from_url('http://ida.omroep.nl/npoplayer/i.js')
..
HTTPError: HTTP Error 410: Gone
   -->End of Python script error report<--

Indeed:
~$ wget --no-proxy http://ida.omroep.nl/npoplayer/i.js
--2017-03-01 18:18:42--  http://ida.omroep.nl/npoplayer/i.js
Resolving ida.omroep.nl (ida.omroep.nl)... 145.58.33.14
Connecting to ida.omroep.nl (ida.omroep.nl)|145.58.33.14|:80... connected.
HTTP request sent, awaiting response... 410 Gone
2017-03-01 18:18:42 ERROR 410: Gone.

streamlink project has this:
plugin.npo: rewrite of plugin to use the new API #642
https://github.com/streamlink/streamlink/issues/638

https://github.com/streamlink/streamlink/pull/642/commits/588a003327f192aef4d6a4a88519ce4b46743b88

youtube-dl has this:
https://github.com/rg3/youtube-dl/blob/4b8a984c67cdc1b2bfde77398d74096406db9644/youtube_dl/extractor/npo.py

I have no idea how to translate this to the kodi uzg plugin ;(

**Comment by Opvolger** [comment]
Working on it.

**Comment by Opvolger** [comment]
fixxed in 1.3.1

**Comment by 00mul** [comment]
dank Bas, snel gerepareerd
