### ISSUE TITLE
Geen NPO sinds gisteren 21-10 met UZG, noch met Retrospect

### ISSUE THREAD

**Issue by Frambozentaart** [Opvolger/plugin.video.uzg#65]
@Bas²
Geen NPO sinds gisteren 21-10 met UZG, noch met Retrospect
UZG 4.04    Retrospect 5.7.20
RPi 3b+ Libreelec 12.01 Kodi 21.1.0 (Omega)

**Comment by Opvolger** [comment]
probeer eens 4.0.6, ik heb het gistern al opgelost

**Comment by Frambozentaart** [comment]
Weer bedankt Bas
