### ISSUE TITLE
Update addon to correctly show duration

### ISSUE THREAD

**Issue by MartijnKaijser** [Opvolger/plugin.video.uzg#8]
Not sure if it's available but it would be nice to correct add the duration for videos.
Currently it shows 23:55:00  and so on.

Would be great you would also use the setContent and setInfo to correctly fill all available info.
Like done here https://github.com/skipmodea1/plugin.video.dumpert/commit/f513fa2693722febca91a81c90a8ef673386605e#diff-646f799de3e5e963e4e3b778f220b491R113

More info
https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#gad3f9b9befa5f3d2f4683f9957264dbbe
https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14

**Comment by Opvolger** [comment]
k zal er eens naar kijken. zullen blijkbaar andere video's zijn dan ik kijk.ik heb het probleem namelijk niet.

**Comment by jorissteyn** [comment]
You're probably referring to time of broadcast prefixed to every episode title, see issue #13 for more info. The runlength is visible, depending on the skin, somewhere else.

**Comment by Opvolger** [comment]
dit is al gefixt in versie 1.3.2 en 2.0.0 (KODI v18)
